
fullnameOverride: ""
nameOverride: ""

general:
  domain: "REPLACE"
  ingress: 
    type: "nginx"
     ## - Annotations to add to the Ingress resource
    annotations: {}
    ## - Labels to add to the Ingress resource
    labels: {}
    # Certificate options
    tls:
      # TLS certificate secret name
      name: 
      # Cluster cert issuer (ex. Let's Encrypt) name if one exists 
      clusterIssuer:

  coreVersion: "2023.9.0"
  webVersion: "2023.9.0"
  mail:
    replyTo: "REPLACE"
    smtpHost: "REPLACE"
    smtpPort: "587"
    smtpSSL: "false"
  disableUserRegistration: "false"   
  hibpApiKey: "false" 
  admins: "false"
  labels: {}

secrets:
  secretSource: "fromSecret"
  fromEnv: 
    fileName: "envvars.env"
  fromValues: 
    globalSettings__installation__id: "REPLACE"
    globalSettings__installation__key: "REPLACE"
    globalSettings__mail__replyToEmail: "REPLACE"
    globalSettings__mail__smtp__host: "stmp.host"
    globalSettings__mail__smtp__port: "386"
    globalSettings__mail__smtp__ssl: "true"
    globalSettings__sqlServer__connectionString: "Data Source=tcp:bitwarden-mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=REPLACE;Multiple Active Result Sets=False;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True"
    globalSettings__yubico__clientId: "REPLACE"
    globalSettings__yubico__key: "REPLACE"
    # This is the password used to setup the database, this should match what is used in the connection string if using the default database
    SA_PASSWORD: "REPLACE"
  # Specify a secret name which contains the secret values set above. Example given in secret-example.md
  fromSecret:
    secretName: custom-secret

component:
  # The Admin component
  admin:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/admin
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  api:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/api
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  attachments:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/attachments
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  events:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/events
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  icons:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/icons   
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"     
  identity:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/identity  
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  notifications:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/notifications  
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  scim:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/scim   
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  sso:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/sso  
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  web:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwarden/web  
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
volume:
  dataprotection:
    size: "1Gi"
    labels: {}
  attachments:
    size: 1Gi
    labels: {}
  licenses:
    size: 1Gi
    labels: {}

#
# Configure service account
#
serviceAccount: service-account

#
# Configure database
#
database:
  # Labels to add to the MSSQL deployment
  labels: {}
  # Image name, tag, and pull policy
  image:
    name: mcr.microsoft.com/mssql/server
    # Tag of the image to use. (Defaults to general.coreVersion)
    tag: 2019-CU17-ubuntu-20.04
  # The containers are limited to the resources below
  resources:
    requests:
      memory: "2G"
      cpu: "2000m"
    limits:
      memory: "2G"
      cpu: "2500m"   

  # The MSSQL volumes
  volume:
    backups:
      # Storage size
      size: 1Gi
    data:
      # Storage size
      size: 10Gi
    log:
      # Storage size
      size: 10Gi      
