{{- if and .Values.ingressEnabled .Values.certCA }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certCASecretName }}
{{- if .Values.certCAAnnotations }}
  annotations:
{{ toYaml .Values.certCAAnnotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: cacert
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.certCALabels }}
{{ toYaml .Values.certCALabels | indent 4 }}
{{- end }}
type: Opaque
data:
  ca.crt: {{ .Values.certCA }}
{{- end }}
