{{- if not .Values.volume.dataprotection.existingClaim -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.dataprotection" . }}
{{- with .Values.volume.dataprotection.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: dataprotection
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.volume.dataprotection.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.volume.dataprotection.accessMode | quote }}
{{- if .Values.volume.dataprotection.storageClass }}
  storageClassName: {{ .Values.volume.dataprotection.storageClass | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.volume.dataprotection.size }}
{{- end -}}
