{{- if not .Values.volume.dataprotection.existingClaim -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.dataprotection" . }}
{{- with .Values.volume.dataprotection.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: dataprotection
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.volume.dataprotection.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
{{ toYaml .Values.volume.dataprotection.accessModes | indent 4 }}
  storageClassName: {{ .Values.volume.dataprotection.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.dataprotection.size }}
{{- end -}}
