---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dataprotectionVolumeClaimName }}
{{- if .Values.dataprotectionVolumeAnnotations }}
  annotations:
{{ toYaml .Values.dataprotectionVolumeAnnotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: dataprotection
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.dataprotectionVolumeLabels }}
{{ toYaml .Values.dataprotectionVolumeLabels | indent 4 }}
{{- end }}
spec:
  accessModes:
{{ toYaml .Values.dataprotectionVolumeAccessModes | indent 4 }}
  storageClassName: {{ .Values.dataprotectionVolumeStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.dataprotectionVolumeSize }}
