{{- if .Values.eventsInstall }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.eventsServiceName }}
{{- if .Values.eventsServiceAnnotations }}
  annotations:
{{ toYaml .Values.eventsServiceAnnotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: events
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.eventsServiceLabels }}
{{ toYaml .Values.eventsServiceLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.eventsServiceType }}
  ports:
    - name: http-port
      port: {{ .Values.eventsServicePort }}
      targetPort: {{ .Values.eventsServiceTargetPort }}
  selector:
    app.kubernetes.io/component: events
{{- end }}
