{{- if .Values.deployment.icons.enabled }}
---
apiVersion: apps/v1
kind: {{ .Values.deployment.icons.kind }}
metadata:
  name: {{ template "bitwarden.icons" . }}
{{- if .Values.deployment.icons.annotations }}
  annotations:
{{ toYaml .Values.deployment.icons.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: icons
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.deployment.icons.labels }}
{{ toYaml .Values.deployment.icons.labels | indent 4 }}
{{- end }}
spec:
{{- if eq .Values.deployment.icons.kind "Deployment" }}
  replicas: {{ .Values.deployment.icons.replicas }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: icons
  template:
    metadata:
{{- if .Values.deployment.icons.podAnnotations }}
      annotations:
{{ toYaml .Values.deployment.icons.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/component: icons
{{ include "bitwarden.labels" . | indent 8 }}
{{- if .Values.deployment.icons.podLabels }}
{{ toYaml .Values.deployment.icons.podLabels | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ template "bitwarden.icons" . }}
          image: "{{ .Values.deployment.icons.image.name }}:{{ .Values.deployment.icons.image.tag | default .Values.general.coreVersion }}"
          imagePullPolicy: {{ .Values.deployment.icons.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.general.configMapName }}
          env:
            - name: ASPNETCORE_URLS
              value: http://+:{{ .Values.service.icons.targetPort }}
          ports:
            - containerPort: {{ .Values.service.icons.targetPort }}
{{- end }}
