{{- if .Values.ingress.enabled }}
---
{{- if and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "19") }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: ingress
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
    - host: {{ .Values.general.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.routePrefix }}
{{- if .Values.ingress.pathType }}
            pathType: {{ .Values.ingress.pathType }}
{{- end }}
            backend:
{{- if and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "19") }}
              service:
                name: {{ template "bitwarden.proxy" . }}
                port:
                  number: {{ .Values.service.proxy.port }}
{{ else }}
              serviceName: {{ template "bitwarden.proxy" . }}
              servicePort: {{ .Values.service.proxy.port }}
{{- end }}
{{- if .Values.ingress.tls.secret }}
  tls:
    - hosts:
      - {{ .Values.general.domain }}
      secretName: {{ .Values.ingress.tls.secret }}
{{- end }}
{{- end }}
