{{- if eq .Values.databaseType "container" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mssqlDataVolumeClaimName }}
{{- if .Values.mssqlDataVolumeAnnotations }}
  annotations:
{{ toYaml .Values.mssqlDataVolumeAnnotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: mssql-data
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.mssqlDataVolumeLabels }}
{{ toYaml .Values.mssqlDataVolumeLabels | indent 4 }}
{{- end }}
spec:
  accessModes:
{{ toYaml .Values.mssqlDataVolumeAccessModes | indent 4 }}
  storageClassName: {{ .Values.mssqlDataVolumeStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.mssqlDataVolumeSize }}
{{- end }}
