{{- if .Values.deployment.proxy.enabled }}
---
apiVersion: apps/v1
kind: {{ .Values.deployment.proxy.kind }}
metadata:
  name: {{ template "bitwarden.proxy" . }}
{{- if .Values.deployment.proxy.annotations }}
  annotations:
{{ toYaml .Values.deployment.proxy.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: proxy
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.deployment.proxy.labels }}
{{ toYaml .Values.deployment.proxy.labels | indent 4 }}
{{- end }}
spec:
{{- if eq .Values.deployment.proxy.kind "Deployment" }}
  replicas: {{ .Values.deployment.proxy.replicas }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
  template:
    metadata:
{{- if .Values.deployment.proxy.podAnnotations }}
      annotations:
{{ toYaml .Values.deployment.proxy.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/component: proxy
{{ include "bitwarden.labels" . | indent 8 }}
{{- if .Values.deployment.proxy.podLabels }}
{{ toYaml .Values.deployment.proxy.podLabels | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ template "bitwarden.proxy" . }}
          image: "{{ .Values.deployment.proxy.image.name }}:{{ .Values.deployment.proxy.image.tag | default .Values.general.coreVersion }}"
          imagePullPolicy: {{ .Values.deployment.proxy.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.general.configMapName }}
          ports:
            - containerPort: {{ .Values.service.proxy.targetPort }}
          volumeMounts:
            - name: proxy
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: proxy
          configMap:
            name: {{ template "bitwarden.proxy" . }}
{{- end }}
