{{- if .Values.ingressEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingressTLSSecret }}
{{- if .Values.ingressTLSSecretAnnotations }}
  annotations:
{{ toYaml .Values.ingressTLSSecretAnnotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: tls
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.ingressTLSSecretLabels }}
{{ toYaml .Values.ingressTLSSecretLabels | indent 4 }}
{{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certSSL }}
  tls.key: {{ .Values.keySSL }}
{{- end }}
