---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ template "bitwarden.secretProviderClass" . }}
  labels:
    app.kubernetes.io/component: secrets
{{ include "bitwarden.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  provider: {{ .Values.secrets.config.provider }}
  parameters:
    useVMManagedIdentity: {{ .Values.secrets.config.useVMManagedIdentity | quote }}
    userAssignedIdentityID: {{ .Values.secrets.config.userAssignedIdentityID }}
    keyvaultName: {{ .Values.secrets.config.keyvaultName }}
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: {{ .Values.secrets.names.installationId }}
          objectAlias: installationid
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.secrets.names.installationKey }}
          objectAlias: installationkey
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.secrets.names.smtpUsername }}
          objectAlias: smtpusername
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.secrets.names.smtpPassword }}
          objectAlias: smtppassword
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.secrets.config.tenantId }}
  secretObjects:
  - secretName: {{ template "bitwarden.secretProviderClass" . }}-secrets
    type: Opaque
    data:
    - objectName: installationid
      key: globalSettings__installation__id
    - objectName: installationkey
      key: globalSettings__installation__key
    - objectName: smtpusername
      key: globalSettings__mail__smtp__username
    - objectName: smtppassword
      key: globalSettings__mail__smtp__password
