---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "bitwarden.admin" . }}
  labels:
    app.kubernetes.io/component: admin
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.admin.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-port
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/component: admin
    app.kubernetes.io/instance: {{ .Release.Name }}
