---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bitwarden.featureflags" . }}
  labels:
{{ include "bitwarden.labels" . | indent 4 }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
data:
  {{- range $key, $value := $.Values.featureFlags }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

---