---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "bitwarden.icons" . }}
  labels:
    app.kubernetes.io/component: icons
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.icons.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-port
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/component: icons
    app.kubernetes.io/instance: {{ .Release.Name }}
