---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "bitwarden.mssql" . }}
  labels:
    app.kubernetes.io/component: mssql
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.database.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-port
      port: 1433
      targetPort: 1433
  selector:
    app.kubernetes.io/component: mssql
    app.kubernetes.io/instance: {{ .Release.Name }}
