---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cleanup"
  labels:
    app.kubernetes.io/component: post-delete-hook
{{ include "bitwarden.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-cleanup"
      labels:
        app.kubernetes.io/component: post-delete-hook
{{ include "bitwarden.labels" . | indent 8 }}
    spec:
    {{- if .Values.serviceAccount }}
      serviceAccountName: "{{ .Values.serviceAccount }}"
    {{- end }}
      containers:
      - name: delete-resources
        command: [
          "/bin/sh", "-c"
        ]
        args: ['
          kubectl delete configmap {{ .Values.general.configMapName }} -n {{ .Release.Namespace }};
          kubectl delete configmap {{ template "bitwarden.web" . }} -n {{ .Release.Namespace }};
          kubectl delete secret "{{ .Release.Name }}-global-env-secrets" -n {{ .Release.Namespace }};
          kubectl delete secret {{ .Release.Name }}-identity-cert -n {{ .Release.Namespace }};
          kubectl delete secretproviderclass {{ template "bitwarden.secretProviderClass" . }} -n {{ .Release.Namespace }};
          echo "Done"
        ']
        image: "bitnami/kubectl:1.21"
      restartPolicy: Never
