---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "bitwarden.secretProviderClass" . }}
  labels:
    app.kubernetes.io/component: secrets
{{ include "bitwarden.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secrets.config.userAssignedIdentityID }}
    keyvaultName: {{ .Values.secrets.config.keyvaultName }}
    cloudName: "AzurePublicCloud"
    objects: |
      array:
    {{- if not (and .Values.secrets.installation .Values.secrets.installation.id .Values.secrets.installation.key) }}
        - |
          objectName: {{ .Values.secrets.names.installationId }}
          objectAlias: installationid
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.secrets.names.installationKey }}
          objectAlias: installationkey
          objectType: secret
          objectVersion: ""
    {{- end }}
        - |
          objectName: {{ .Values.secrets.names.smtpUsername }}
          objectAlias: smtpusername
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.secrets.names.smtpPassword }}
          objectAlias: smtppassword
          objectType: secret
          objectVersion: ""
    tenantId: "10c0387a-9792-4d9f-b1b1-ebc6785914ce"
  secretObjects:
  - secretName: {{ template "bitwarden.secretProviderClass" . }}-secrets
    type: Opaque
    data:
  {{- if not (and .Values.secrets.installation .Values.secrets.installation.id .Values.secrets.installation.key) }}
    - objectName: installationid
      key: globalSettings__installation__id
    - objectName: installationkey
      key: globalSettings__installation__key
  {{- end }}
    - objectName: smtpusername
      key: globalSettings__mail__smtp__username
    - objectName: smtppassword
      key: globalSettings__mail__smtp__password
