#########################
# Bitwarden App Volumes #
#########################

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.attachments" . }}
  labels:
    app.kubernetes.io/component: attachments
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.attachments.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.component.attachments.volume.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.licenses" . }}
  labels:
    app.kubernetes.io/component: licenses
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.volume.licenses.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.licenses.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.dataprotection" . }}
  labels:
    app.kubernetes.io/component: dataprotection
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.volume.dataprotection.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.dataprotection.size }}


#################
# MSSQL Volumes #
#################

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.mssqlLog" . }}
  labels:
    app.kubernetes.io/component: mssql-log
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.database.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.database.volume.log.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.mssqlBackups" . }}
  labels:
    app.kubernetes.io/component: mssql-backups
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.database.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.database.volume.backups.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bitwarden.mssqlData" . }}
  labels:
    app.kubernetes.io/component: mssql-data
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.database.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.database.volume.data.size }}
