{{- if not .Values.serviceAccountName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bitwarden.serviceAccountName" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
    helm.sh/hook-delete-policy: hook-succeeded
{{- if .Values.serviceAccountAnnotations }}
{{ toYaml .Values.serviceAccountAnnotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: rbac
{{ include "bitwarden.labels" . | indent 4 }}
{{- if .Values.serviceAccountLabels }}
{{ toYaml .Values.serviceAccountLabels | indent 4 }}
{{- end }}
{{- end -}}
