apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}   
  namespace: {{ .Release.Namespace }}   
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role:service-acc
  namespace: {{ .Release.Namespace }}  
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"    
rules:          # Authorization rules for this role
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding:service-acc
  namespace: {{ .Release.Namespace }}  
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role:service-acc
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}   
    namespace: {{ .Release.Namespace }}      