{{- if eq .Values.secrets.secretSource "fromEnv" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-globalsettings-env-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- $v := $.Files.Get "{{ .Values.secrets.fromEnv.fileName }}" | fromYaml }}
{{- range $key, $val := $v }}
{{ $key | indent 2 }}: {{ $val | toString | b64enc }}
{{- end}}

{{- end}}

{{- if eq .Values.secrets.secretSource "fromValues" }}

{{- $dbPasswordTxtValue := (randAlphaNum 32) }}
{{- $dbServiceName := include "bitwarden.mssql" . }}
{{- $dbConnectionStringValue := printf "Data Source=tcp:%s,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True" $dbServiceName $dbPasswordTxtValue }}

{{- $currentGlobalEnvSecrets := (lookup "v1" "Secret" .Release.Namespace "{{ .Release.Name }}-global-env-secrets") }}
{{- if $currentGlobalEnvSecrets }}
{{- $identityCertPasswordTxtValue := index $currentGlobalEnvSecrets.data "globalSettings__identityServer__certificatePassword" | b64dec }}
{{- $dbConnectionStringValue := index $currentGlobalEnvSecrets.data "globalSettings__sqlServer__connectionString" | b64dec }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-globalsettings-env-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  globalSettings__installation__id: {{ default "" .Values.secrets.fromValues.globalSettings__installation__id | toString | b64enc }}
  globalSettings__installation__key: {{ default "" .Values.secrets.fromValues.globalSettings__installation__key | toString | b64enc }}
  globalSettings__mail__replyToEmail: {{ default "" .Values.secrets.fromValues.globalSettings__mail__replyToEmail | toString | b64enc }}
  globalSettings__mail__smtp__host: {{ default "" .Values.secrets.fromValues.globalSettings__mail__smtp__host | toString | b64enc }}
  globalSettings__mail__smtp__port: {{ default "" .Values.secrets.fromValues.globalSettings__mail__smtp__port | toString | b64enc }}
  globalSettings__mail__smtp__ssl: {{ default "" .Values.secrets.fromValues.globalSettings__mail__smtp__ssl | toString | b64enc }}
  globalSettings__yubico__clientId: {{ default "" .Values.secrets.fromValues.globalSettings__yubico__clientId | toString | b64enc }}
  globalSettings__yubico__key: {{ default "" .Values.secrets.fromValues.globalSettings__yubico__key | toString | b64enc }}
  globalSettings__sqlServer__connectionString: {{ default $dbConnectionStringValue .Values.secrets.fromValues.globalSettings__sqlServer__connectionString | toString | b64enc }}
  SA_PASSWORD: {{ default "" .Values.secrets.fromValues.SA_PASSWORD | toString | b64enc }}
{{- end}}