{{- if not .Values.selfHosted }}
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: {{ .Release.Name | lower | replace " " "-" }}
  labels:
    app.kubernetes.io/component: pre-install-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  forProvider:
    location: "East US"
    tags:
      managedBy: "Helm"
      environment: "{{ .Release.Name }}"
{{- end }}
