---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-pre-upgrade"
  labels:
    app.kubernetes.io/component: pre-install-db-migrator-job
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.job.db.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
{{- if .Values.database.enabled }}
    "helm.sh/hook": pre-upgrade
{{- else }}
    "helm.sh/hook": pre-install,pre-upgrade
{{- end }}
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
{{- include "bitwarden.annotations" . | indent 4 }}
{{- with .Values.job.db.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-db-pre-upgrade"
      labels:
        app.kubernetes.io/component: pre-install-db-migrator-job
{{ include "bitwarden.podLabels" . | indent 8 }}
{{- with .Values.job.db.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
      annotations:
{{- include "bitwarden.podAnnotations" . | indent 8 }}
{{- with .Values.job.db.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
      {{- end }}
      containers:
      - name: migrate-db
        env:
        - name: MSSQL_CONN_STRING
          valueFrom:
            secretKeyRef:
              {{- if .Values.database.enabled }}
              name: {{ .Release.Name }}-sql-connection-string
              {{- else }}
              name: "{{ .Values.secrets.secretName }}"
              {{- end }}
              key: globalSettings__sqlServer__connectionString
        image: "{{ .Values.supportComponents.dbMigrator.image.name }}:{{default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride }}"
        volumeMounts:
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
      restartPolicy: Never
      volumes:
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secrets.secretProviderClass }}
        {{- end }}
