{{- if .Values.volume.dataprotection -}}
{{- if not .Values.volume.dataprotection.existingClaim -}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "bitwarden.dataprotection" . }}
spec:
  accessModes:
    - {{ .Values.general.volumeAccessMode }}
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.dataprotection.size }}
{{- end -}}
{{- end -}}

{{- if .Values.volume.licenses }}
{{- if not .Values.volume.licenses.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "bitwarden.licenses" . }}
  labels:
    app.kubernetes.io/component: licenses
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.volume.licenses.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.general.volumeAccessMode }}
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.licenses.size }}
{{- end -}}
{{- end -}}

{{- if .Values.volume.attachments }}
{{- if not .Values.volume.attachments.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "bitwarden.attachmentsVolume" . }}
  labels:
    app.kubernetes.io/component: attachments
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.volume.attachments.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.general.volumeAccessMode }}
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.attachments.size }}
{{- end -}}
{{- end -}}

{{- if .Values.volume.logs }}
{{- if .Values.volume.logs.enabled }}
{{- if not .Values.volume.logs.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "bitwarden.applogs" . }}
  labels:
    app.kubernetes.io/component: logs
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.volume.logs.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.general.volumeAccessMode }}
  storageClassName: {{ .Values.sharedStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.volume.logs.size }}
{{- end }}
{{- end }}
{{- end }}

#################
# MSSQL Volumes #
#################
{{- if .Values.database.enabled }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "bitwarden.mssqlLog" . }}
  labels:
    app.kubernetes.io/component: mssql-log
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.database.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{ template "bitwarden.dbStorageClass" . }}
  resources:
    requests:
      storage: {{ .Values.database.volume.log.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "bitwarden.mssqlBackups" . }}
  labels:
    app.kubernetes.io/component: mssql-backups
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.database.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{ template "bitwarden.dbStorageClass" . }}
  resources:
    requests:
      storage: {{ .Values.database.volume.backups.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "bitwarden.mssqlData" . }}
  labels:
    app.kubernetes.io/component: mssql-data
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.database.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{ template "bitwarden.dbStorageClass" . }}
  resources:
    requests:
      storage: {{ .Values.database.volume.data.size }}
{{- end }}
