apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitwarden.api" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bitwarden.api" . }}
    app.kubernetes.io/component: api
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.api.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "bitwarden.api" . }}
  template:
    metadata:
      labels:
        app: {{ template "bitwarden.api" . }}
        app.kubernetes.io/component: api
{{ include "bitwarden.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "bitwarden.api" . }}
        image: "{{ .Values.component.api.image.name }}:{{ .Values.general.coreVersion }}"
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config-map
          - secretRef:
              name: "{{ .Values.secrets.secretName }}"
          {{- if .Values.database.enabled }}
          - secretRef:
              name: {{ .Release.Name }}-sql-connection-string
          {{- end }}
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5000
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 180
        ports:
        - containerPort: 5000
        resources:
{{ toYaml .Values.component.api.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/bitwarden/core/attachments
          name: attachments
        - mountPath: /etc/bitwarden/core/aspnet-dataprotection
          name: dataprotection
        - mountPath: /etc/bitwarden/core/licenses
          name: licenses
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
      volumes:
        - name: dataprotection
          persistentVolumeClaim:
            claimName: {{ template "bitwarden.dataprotection" . }}
        - name: attachments
          persistentVolumeClaim:
            claimName: {{ template "bitwarden.attachments" . }}
        - name: licenses
          persistentVolumeClaim:
            claimName: {{ template "bitwarden.licenses" . }}
        {{- if .Values.secrets.secretProviderClass}}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secrets.secretProviderClass }}
        {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitwarden.api" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: api
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.api.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    app: {{ template "bitwarden.api" . }}
  ports:
  - port: 5000
    targetPort: 5000

