apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitwarden.attachments" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bitwarden.attachments" . }}
    app.kubernetes.io/component: attachments
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.attachments.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "bitwarden.attachments" . }}
  template:
    metadata:
      labels:
        app: {{ template "bitwarden.attachments" . }}
        app.kubernetes.io/component: attachments
{{ include "bitwarden.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "bitwarden.attachments" . }}
        image: "{{ .Values.component.attachments.image.name }}:{{ .Values.general.coreVersion }}"
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config-map
          - secretRef:
              {{- if eq .Values.secrets.secretSource "fromValues" }}
              name: {{ .Release.Name }}-globalsettings-env-secrets
              {{- end }}
              {{- if eq .Values.secrets.secretSource "fromSecret" }}
              name: "{{ .Values.secrets.fromSecret.secretName }}"
              {{- end }}                           
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5000
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 180    
        ports:
        - containerPort: 5000
        resources:
{{ toYaml .Values.component.attachments.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/bitwarden/core/attachments    
          name: attachments               
      volumes:
        - name: attachments
          persistentVolumeClaim:
            claimName: {{ template "bitwarden.attachments" . }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitwarden.attachments" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "bitwarden.attachments" . }}
    app.kubernetes.io/component: attachments
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.attachments.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
  - port: 5000
    targetPort: 5000

