---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "bitwarden.ingress" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if eq .Values.general.ingress.type "nginx" }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- end }} 
    {{- if .Values.general.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: .Values.general.ingress.tls.clusterIssuer
    {{- end }} 
{{- with .Values.general.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: ingress
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.general.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.general.domain }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.web" . }}
                port:
                  number: 5000
          - path: /(app-id.json)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.web" . }}
                port:
                  number: 5000


          - path: /(duo-connector.html)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.web" . }}
                port:
                  number: 5000


          - path: /(u2f-connector.html)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.web" . }}
                port:
                  number: 5000


          - path: /(webauthn-connector.html)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.web" . }}
                port:
                  number: 5000


          - path: /(webauthn-fallback-connector.html)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.web" . }}
                port:
                  number: 5000


          - path: /(sso-connector.html)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.web" . }}
                port:
                  number: 5000


          - path: /attachments[/|$](.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.attachments" . }}
                port:
                  number: 5000


          - path: /api[/|$](.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.api" . }}
                port:
                  number: 5000


          - path: /icons[/|$](.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.icons" . }}
                port:
                  number: 5000


          - path: /notifications[/|$](.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.notifications" . }}
                port:
                  number: 5000


          - path: /events[/|$](.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.events" . }}
                port:
                  number: 5000


          - path: /sso[/|$](.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.sso" . }}
                port:
                  number: 5000


          - path: /identity[/|$](.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.identity" . }}
                port:
                  number: 5000


          - path: /(admin[/|$].*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "bitwarden.admin" . }}
                port:
                  number: 5000

  tls:
    - hosts:
      - {{ .Values.general.domain }}
      {{- if .Values.general.ingress.tls.name }}
      secretName: {{ .Values.general.ingress.tls.name }}
      {{- end }} 