
{{- $dbServiceName := include "bitwarden.mssql" . }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sql-connection-string
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
type: Opaque
data:
{{- if or (eq .Values.secrets.secretSource "fromValues") (eq .Values.secrets.secretSource "fromEnv") }}
{{- $currentGlobalEnvSecrets := (lookup "v1" "Secret" .Release.Namespace "{{ .Release.Name }}-global-env-secrets") }}
{{- if $currentGlobalEnvSecrets }}
{{- $dbPasswordTxtValue := index $currentGlobalEnvSecrets.data "SA_PASSWORD" | b64dec }}
{{- $dbConnectionStringValue := printf "Data Source=tcp:%s,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True" $dbServiceName $dbPasswordTxtValue }}
  globalSettings__sqlServer__connectionString: {{ $dbConnectionStringValue | toString | b64enc }}
{{- end }}
{{- end }}

{{- if eq .Values.secrets.secretSource "fromSecret" }}
{{- $currentGlobalEnvSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.secrets.fromSecret.secretName) }}
{{- if $currentGlobalEnvSecrets }}
{{- $dbPasswordTxtValue := index $currentGlobalEnvSecrets.data "SA_PASSWORD" | b64dec }}
{{- $dbConnectionStringValue := printf "Data Source=tcp:%s,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True" $dbServiceName $dbPasswordTxtValue }}
  globalSettings__sqlServer__connectionString: {{ $dbConnectionStringValue | toString | b64enc }}
{{- end }}
{{- end }}