{{- if eq .Values.secrets.secretSource "fromEnv" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-globalsettings-env-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
type: Opaque
data:
{{- $v := $.Files.Get "{{ .Values.secrets.fromEnv.fileName }}" | fromYaml }}
{{- range $key, $val := $v }}
{{ $key | indent 2 }}: {{ $val | toString | b64enc }}
{{- end}}

{{- end}}

{{- if eq .Values.secrets.secretSource "fromValues" }}

{{- $dbPasswordTxtValue := (randAlphaNum 32) }}
{{- $dbServiceName := include "bitwarden.mssql" . }}
{{- $currentGlobalEnvSecrets := (lookup "v1" "Secret" .Release.Namespace "{{ .Release.Name }}-global-env-secrets") }}
{{- if $currentGlobalEnvSecrets }}
{{- $identityCertPasswordTxtValue := index $currentGlobalEnvSecrets.data "globalSettings__identityServer__certificatePassword" | b64dec }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-globalsettings-env-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
type: Opaque
data:
  globalSettings__installation__id: {{ .Values.secrets.fromValues.globalSettings__installation__id | default "" | toString | b64enc }}
  globalSettings__installation__key: {{ .Values.secrets.fromValues.globalSettings__installation__key | default "" | toString | b64enc }}
  globalSettings__mail__replyToEmail: {{ .Values.secrets.fromValues.globalSettings__mail__replyToEmail | default "" | toString | b64enc }}
  globalSettings__mail__smtp__host: {{ .Values.secrets.fromValues.globalSettings__mail__smtp__host | default "" | toString | b64enc }}
  globalSettings__mail__smtp__port: {{ .Values.secrets.fromValues.globalSettings__mail__smtp__port | default "" | toString | b64enc }}
  globalSettings__mail__smtp__ssl: {{ .Values.secrets.fromValues.globalSettings__mail__smtp__ssl | default "" | toString | b64enc }}
{{- if and .Values.secrets.fromValues.globalSettings__mail__smtp__username .Values.secrets.fromValues.globalSettings__mail__smtp__password }}
  globalSettings__mail__smtp__username: {{ .Values.secrets.fromValues.globalSettings__mail__smtp__username | default "" | toString | b64enc }}
  globalSettings__mail__smtp__password: {{ .Values.secrets.fromValues.globalSettings__mail__smtp__password | default "" | toString | b64enc }}
{{- end }}
{{- if and .Values.secrets.fromValues.globalSettings__yubico__clientId .Values.secrets.fromValues.globalSettings__yubico__key }}
  globalSettings__yubico__clientId: {{ .Values.secrets.fromValues.globalSettings__yubico__clientId | default "" | toString | b64enc }}
  globalSettings__yubico__key: {{ .Values.secrets.fromValues.globalSettings__yubico__key | default "" | toString | b64enc }}
{{- end }}
{{- if .Values.database.enabled }}
  SA_PASSWORD: {{ .Values.secrets.fromValues.SA_PASSWORD | default "" | toString | b64enc }}
{{- else }}
  globalSettings__sqlServer__connectionString: {{ .Values.secrets.fromValues.globalSettings__sqlServer__connectionString | default "" | toString | b64enc }}
{{- end }}
{{- end }}