{{- if .Values.database.enabled }}
{{- $dbServiceName := include "bitwarden.mssql" . }}


apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-secret-sql"
  labels:
    app.kubernetes.io/component: pre-install-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-secret-sql"
      labels:
        app.kubernetes.io/component: pre-install-hook
    spec:
    {{- if .Values.serviceAccount }}
      serviceAccountName: "{{ .Values.serviceAccount }}"
    {{- end }}
      containers:
      - name: create-resources
        command:
          - "/bin/sh"
          - "-c"
        args: ['
          kubectl create secret generic {{ .Release.Name }}-sql-connection-string -n {{ .Release.Namespace }}
            --from-literal=globalSettings__sqlServer__connectionString="Data Source=tcp:{{ $dbServiceName }},1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=$SA_PASSWORD;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True"

          echo "Done"
        ']
        image: "bitnami/kubectl:1.21"
        envFrom:
          - secretRef:
              {{- if or (eq .Values.secrets.secretSource "fromValues") (eq .Values.secrets.secretSource "fromEnv") }}
              name: {{ .Release.Name }}-globalsettings-env-secrets
              {{- end }}
              {{- if eq .Values.secrets.secretSource "fromSecret" }}
              name: "{{ .Values.secrets.fromSecret.secretName }}"
              {{- end }}
        volumeMounts:
        - name: temp
          mountPath: "/bitwarden"
        {{- if .Values.secrets.fromSecret.secretProviderClass}}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
      restartPolicy: Never
      volumes:
        - name: temp
          emptyDir:
            medium: Memory
        {{- if .Values.secrets.fromSecret.secretProviderClass}}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secrets.fromSecret.secretProviderClass }}
        {{- end }}
{{- end }}