apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitwarden.web" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bitwarden.web" . }}
    app.kubernetes.io/component: web
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.web.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "bitwarden.web" . }}
  template:
    metadata:
      labels:
        app: {{ template "bitwarden.web" . }}
        app.kubernetes.io/component: web
{{ include "bitwarden.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "bitwarden.web" . }}
        image: "{{ .Values.component.web.image.name }}:{{ .Values.general.webVersion }}"
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-config-map
          - secretRef:
              {{- if eq .Values.secrets.secretSource "fromValues" }}
              name: {{ .Release.Name }}-globalsettings-env-secrets
              {{- end }}
              {{- if eq .Values.secrets.secretSource "fromSecret" }}
              name: "{{ .Values.secrets.fromSecret.secretName }}"
              {{- end }}
          {{- if .Values.database.enabled }}
          - secretRef:
              name: {{ .Release.Name }}-sql-connection-string
          {{- end }}
        env:
          - name: ASPNETCORE_URLS
            value: http://+:5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 180
        ports:
        - containerPort: 5000
        resources:
{{ toYaml .Values.component.web.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/bitwarden/web
          name: web
        {{- if .Values.secrets.fromSecret.secretProviderClass}}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
      volumes:
        - name: web
          configMap:
            name: {{ .Release.Name }}-config-map-web
        {{- if .Values.secrets.fromSecret.secretProviderClass}}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secrets.fromSecret.secretProviderClass }}
        {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitwarden.web" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: web
{{ include "bitwarden.labels" . | indent 4 }}
{{- with .Values.component.web.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    app: {{ template "bitwarden.web" . }}
  ports:
  - port: 5000
    targetPort: 5000

