# Default values for bitwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "ee"
#
# General configuration options
#
general:
  coreVersion: "1.47.1"
  webVersion: "2.27.0"
  keyconnectorVersion: "1.0.1"
  # Labels to apply to all resources
  labels: {}
    # label1: value1
    # label2: value2
  configMapName: config
  # Domain used for Bitwarden installation
  domain: "bitwarden.localhost"
  yubico:
    clientId: ""
    key: ""
    validationURLs: []
  email:
    replyToEmail: "no-reply@bitwarden.localhost"
    smtpHost: "smtp.sendgrid.net"
    smtpPort: "587"
    smtpSsl: "false"
  # Specify the number of hours after which an Organization Invite will expire (120 by default)
  organizationInviteExpirationHours: "120"
  disableUserRegistration: "false"
  hibp:
    apiKey: ""
  admins: ""

#
# Feature flags are environment variables that get set on all the Bitwarden containers.
# Values are optional and adding additional ones is supported!
#
featureFlags:
  EE_TESTING_ENV: ""

#
# Configure service account
#
serviceAccount: ee-bot-service-account

#
# Configure secrets
#
secrets:
  # CSI Configuration
  config:
    keyvaultName: bw-ee-bot
    userAssignedIdentityID: "8e6b6ba5-20bd-47d3-bb61-5dec822dcd58"
  # installation id and key. If not supplied default values from Key Vault will be used
  installation:
    id: ""
    key: ""
  # Key Vault Secret Names
  names:
    installationId: ee-installation-id
    installationKey: ee-installation-key
    smtpUsername: ee-smtp-username
    smtpPassword: ee-smtp-password

#
#  Configure ingress
#
ingress:
  ## - Annotations to add to the Ingress resource
  annotations: {}
  ## - Labels to add to the Ingress resource
  labels: {}
  # Certificate options
  tls:
    # TLS certificate secret name
    name: eph-wildcard

#
# Configure database
#
database:
  # Labels to add to the MSSQL deployment
  labels: {}
  # Image name, tag, and pull policy
  image:
    name: mcr.microsoft.com/mssql/server
    # Tag of the image to use. (Defaults to general.coreVersion)
    tag: 2017-CU18-ubuntu-16.04
  # The containers are limited to the resources below
  resources:
    limits:
      memory: 1Gi

  # The MSSQL volumes
  volume:
    backups:
      # Storage size
      size: 1Gi
    data:
      # Storage size
      size: 10Gi
    log:
      # Storage size
      size: 10Gi

#
# Configure Webhook
#
webhook:
  labels: {}
  # Annotations to add to the Webhook deployment pods
  # Image name, tag, and pull policy
  image:
    name: bitwardenqa.azurecr.io/backup-webhook
    # Tag of the image to use. (Defaults to general.coreVersion)
    tag: "dev"
  env:
    # Azure Storage Account Connection String
    azureStorageConnectionString: ""
    # Webhook API Key
    webhookApiKey: This-really-should-be-changed  # Should this be a secret in a Key Vault and shared by all of the environments?
    # Server Branch for SQL migration files
    serverBranch: master # This will need to be examined. Can't use coreVersion since the slashes are converted into dashes for the docker image name

#
# Configure components
#
component:
  # The Admin component
  admin:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/admin

  # The API component
  api:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/api

  # The Attachments component
  attachments:
    # Additional deployment annotations
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/attachments
    volume:
      # Storage size
      size: 1Gi

  # The Events component
  events:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/events

  # The Icons component
  icons:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/icons

  # The Identity component
  identity:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/identity

  # The Notifications component
  notifications:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/notifications

  # The SSO component
  sso:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/sso

  # The Web component
  web:
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/web-ee

  # The SCIM component
  scim:
    # Additional deployment labels
    labels: {}
    # Image name, tag, and pull policy
    image:
      name: bitwardenqa.azurecr.io/scim

#
# Configure other volumes
#
volume:
  dataprotection:
    labels: {}
    # Storage size
    size: 1Gi
  licenses:
    # Additional volume labels
    labels: {}
    # Storage size
    size: 1Gi

#
# Configure shared storage class
#
sharedStorageClassName: ee-shared-storageclass