---
name: Build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build Helm chart
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Helm
        uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Helm chart
        run: helm lint charts/self-host

      - name: Package Helm chart
        id: helm_package
        run: |
          helm package charts/self-host
          PKG_NAME=$(ls *.tgz)
          echo "name=$PKG_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: self-host
          path: ${{ steps.helm_package.outputs.name }}
          if-no-files-found: error
