# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  #  branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ACR_REGISTRY: bwhelmtest
  ACR_REGISTRY_USER: bwhelmtest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Beta
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Helm tool installer
        uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 #v3

      # Runs a single command using the runners shell
      - name: helm lint
        run: helm lint ./bitwarden-self-host

      # Runs a set of commands using the runners shell
      - name: helm package 
        id: helm_package
        run: |
          rm -f bitwarden-*.tgz
          helm package ./bitwarden-self-host
          path=$(ls bitwarden-*.tgz)
          echo "path=$path" >> "$GITHUB_OUTPUT"
          
      - name: helm push
        run: |
          echo ${{steps.helm_package.outputs.path}}
          registry="${{ env.ACR_REGISTRY }}.azurecr.io"
          echo "${{ secrets.ACR_PASSWORD }}" | helm registry login $registry -u ${{ env.ACR_REGISTRY_USER }} --password-stdin
          helm push ${{steps.helm_package.outputs.path}} oci://$registry/helm
      
        
