---
name: Lint

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Helm charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: 'v3.13.1'

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.12'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@b43128a8b25298e1e7b043b78ea6613844e079b1 # v2.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          CHANGED=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$CHANGED" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        env:
          CT_CHECK_VERSION_INCREMENT: false
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        #if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Setup cluster
        #if: steps.list-changed.outputs.changed == 'true'
        run: | 
          mkdir ${GITHUB_WORKSPACE}/storage
          kubectl create ns bitwarden
          echo << EOF | kubectl apply -n bitwarden -f -
            apiVersion: storage.k8s.io/v1
            kind: StorageClass 
            metadata:   
              name: shared-storage
            provisioner: docker.io/hostpath

            ---
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: shared-pv-1
              labels:
                type: local
            spec:
              storageClassName: shared-storage
              capacity:
                storage: 10Gi
              accessModes:
                - ReadWriteMany
              hostPath:
                path: ${GITHUB_WORKSPACE}/storage/
              persistentVolumeReclaimPolicy: Retain
            
            ---
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: shared-pv-2
              labels:
                type: local
            spec:
              storageClassName: shared-storage
              capacity:
                storage: 10Gi
              accessModes:
                - ReadWriteMany
              hostPath:
                path: ${GITHUB_WORKSPACE}/storage/
              persistentVolumeReclaimPolicy: Retain
            ---
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: shared-pv-3
              labels:
                type: local
            spec:
              storageClassName: shared-storage
              capacity:
                storage: 10Gi
              accessModes:
                - ReadWriteMany
              hostPath:
                path: ${GITHUB_WORKSPACE}/storage/
              persistentVolumeReclaimPolicy: Retain
            ---
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: shared-pv-4
              labels:
                type: local
            spec:
              storageClassName: shared-storage
              capacity:
                storage: 1Gi
              accessModes:
                - ReadWriteMany
              hostPath:
                path: ${GITHUB_WORKSPACE}/storage/
              persistentVolumeReclaimPolicy: Retain
            ---
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: shared-pv-5
              labels:
                type: local
            spec:
              storageClassName: shared-storage
              capacity:
                storage: 1Gi
              accessModes:
                - ReadWriteMany
              hostPath:
                path: ${GITHUB_WORKSPACE}/storage/
              persistentVolumeReclaimPolicy: Retain
            ---
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: shared-pv-6
              labels:
                type: local
            spec:
              storageClassName: shared-storage
              capacity:
                storage: 1Gi
              accessModes:
                - ReadWriteMany
              hostPath:
                path: ${GITHUB_WORKSPACE}/storage/
              persistentVolumeReclaimPolicy: Retain
            ---
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: shared-pv-7
              labels:
                type: local
            spec:
              storageClassName: shared-storage
              capacity:
                storage: 1Gi
              accessModes:
                - ReadWriteMany
              hostPath:
                path: ${GITHUB_WORKSPACE}/storage/
              persistentVolumeReclaimPolicy: Retain
          EOF
