# This is a basic workflow to help you get started with Actions

name: Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 
     
      - name: Fetch history
        run: git fetch --prune --unshallow
        
      - name: Helm tool installer
        uses: Azure/setup-helm@v3 #TODO:  Pin to a specific commit instead of tag for DevSecOps safety
        with:
          # Version of helm
          version: v3.12.3
      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs . --excluded-charts bitwarden,integration-chart,ephemeral-env-1.0.0,ephemeral-env-1.4.8 --target-branch ${{ github.event.repository.default_branch }}) #${GITHUB_REF#refs/heads/}
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs ./bitwarden-self-host --charts ./bitwarden-self-host --target-branch ${{ github.event.repository.default_branch }}
       
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Setup volumes        
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          mkdir $GITHUB_WORKSPACE/shared

          cat <<EOF | kubectl apply -n bitwarden -f -
          apiVersion: storage.k8s.io/v1
          kind: StorageClass 
          metadata:   
            name: shared-storage
          provisioner: docker.io/hostpath
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: bitwarden-shared-pv-1
            labels:
              type: local
          spec:
            storageClassName: shared-storage
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteMany
            hostPath:
              path: $GITHUB_WORKSPACE/shared
            persistentVolumeReclaimPolicy: Retain
          
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: bitwarden-shared-pv-2
            labels:
              type: local
          spec:
            storageClassName: shared-storage
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteMany
            hostPath:
              path: $GITHUB_WORKSPACE/shared
            persistentVolumeReclaimPolicy: Retain
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: bitwarden-shared-pv-3
            labels:
              type: local
          spec:
            storageClassName: shared-storage
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteMany
            hostPath:
              path: $GITHUB_WORKSPACE/shared
            persistentVolumeReclaimPolicy: Retain
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: bitwarden-shared-pv-4
            labels:
              type: local
          spec:
            storageClassName: shared-storage
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteMany
            hostPath:
              path: $GITHUB_WORKSPACE/shared
            persistentVolumeReclaimPolicy: Retain
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: bitwarden-shared-pv-5
            labels:
              type: local
          spec:
            storageClassName: shared-storage
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteMany
            hostPath:
              path: $GITHUB_WORKSPACE/shared
            persistentVolumeReclaimPolicy: Retain
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: bitwarden-shared-pv-6
            labels:
              type: local
          spec:
            storageClassName: shared-storage
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteMany
            hostPath:
              path: $GITHUB_WORKSPACE/shared
            persistentVolumeReclaimPolicy: Retain
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: bitwarden-shared-pv-7
            labels:
              type: local
          spec:
            storageClassName: shared-storage
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteMany
            hostPath:
              path: $GITHUB_WORKSPACE/shared
            persistentVolumeReclaimPolicy: Retain
          EOF

          kubectl get pv -n bitwarden

      - name: Run chart-testing (install)        
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --debug --chart-dirs ./bitwarden-self-host --charts ./bitwarden-self-host --target-branch main
