---
name: Lint

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Helm charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
          dotnet-version: 6.x
      
      - name: Set up Helm
        uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: 'v3.13.1'

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.12'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@b43128a8b25298e1e7b043b78ea6613844e079b1 # v2.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          CHANGED=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$CHANGED" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        env:
          CT_CHECK_VERSION_INCREMENT: false
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        #if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Setup cluster
        #if: steps.list-changed.outputs.changed == 'true'
        run: |
          dotnet tool install -g dotnet-guid
        
          kubectl create ns bitwarden

          installation_id=$(guid -d)
          installation_key=$(openssl rand -base64 12)
          sa_password=$(openssl rand -base64 12)
          kubectl create secret generic custom-secret -n bitwarden\
            --from-literal=globalSettings__installation__id=$installation_id \
            --from-literal=globalSettings__installation__key=$installation_key \
            --from-literal=globalSettings__mail__smtp__username="REPLACE" \
            --from-literal=globalSettings__mail__smtp__password="REPLACE" \
            --from-literal=globalSettings__yubico__clientId="REPLACE" \
            --from-literal=globalSettings__yubico__key="REPLACE" \
            --from-literal=SA_PASSWORD=$sa_password

          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

      - name: Run chart-testing (install)
        # if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --namespace bitwarden
