name: Linter

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  RUN_TESTS: false
  
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
     
      - name: Fetch history
        run: git fetch --prune --unshallow
        
      - name: Helm tool installer
        uses: Azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 #v3
        with:
          # Version of helm
          version: v3.12.3
          
      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 #v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 #v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs . --excluded-charts bitwarden,integration-chart,ephemeral-env-1.0.0,ephemeral-env-1.4.8 --target-branch ${{ github.event.repository.default_branch }}) #${GITHUB_REF#refs/heads/}
          if [["$RUN_TESTS" = true] && [ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs ./bitwarden-self-host --charts ./bitwarden-self-host --target-branch ${{ github.event.repository.default_branch }}
       
      - name: Create kind cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 #v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)        
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --debug --chart-dirs ./bitwarden-self-host --charts ./bitwarden-self-host --target-branch main
