---
name: Update Versions

on:
  workflow_dispatch:

env:
  _BRANCH: main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    outputs:
      core_version: ${{ steps.get-core.outputs.version }}
      core_version_update: ${{ steps.core-update.outputs.update }}
      web_version: ${{ steps.get-web.outputs.version }}
      web_version_update: ${{ steps.web-update.outputs.update }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env._BRANCH }}

      - name: Get Latest Core Version
        id: get-core
        uses: bitwarden/gh-actions/get-release-version@master
        with:
          repository: bitwarden/server
          trim: true

      - name: Check if Core Version needs updating
        id: core-update
        env:
          LATEST_CORE_VERSION: ${{ steps.get-core.outputs.version }}
        run: |
          CORE_VERSION=$(sed -r -n '/define "bitwarden.coreVersionDefault"/!b;n;'\
          's/\{\{- "([0-9]+\.[0-9]+\.[0-9]+)" -\}\}/\1/p' helpers.tpl)

          echo "Core Version: $CORE_VERSION"
          echo "Latest Core Version: $LATEST_CORE_VERSION"
          if [ "$CORE_VERSION" != "$LATEST_CORE_VERSION" ]; then
            echo "Needs Core update!"
            echo "update=1" >> $GITHUB_OUTPUT
          else
            echo "update=0" >> $GITHUB_OUTPUT
          fi
        working-directory: charts/self-host/templates

      - name: Get Latest Web Version
        id: get-web
        uses: bitwarden/gh-actions/get-release-version@master
        with:
          repository: bitwarden/clients
          monorepo: true
          monorepo-project: web
          trim: true

      - name: Check if Web Version needs updating
        id: web-update
        env:
          LATEST_WEB_VERSION: ${{ steps.get-web.outputs.version }}
        run: |
          WEB_VERSION=$(sed -r -n '/define "bitwarden.webVersionDefault"/!b;n;'\
          's/\{\{- "([0-9]+\.[0-9]+\.[0-9]+)" -\}\}/\1/p' helpers.tpl)

          echo "Web Version: $WEB_VERSION"
          echo "Latest Web Version: $LATEST_WEB_VERSION"
          if [ "$WEB_VERSION" != "$LATEST_WEB_VERSION" ]; then
            echo "Needs Web update!"
            echo "update=1" >> $GITHUB_OUTPUT
          else
            echo "update=0" >> $GITHUB_OUTPUT
          fi
        working-directory: charts/self-host/templates

  update-versions:
    name: "Update Versions"
    if: |
      needs.setup.outputs.core_version_update == 1 ||
      needs.setup.outputs.web_version_update == 1
    runs-on: ubuntu-22.04
    needs: setup
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env._BRANCH }}

      - name: Create Update Versions Branch
        run: |
          PR_BRANCH=update-versions-$GITHUB_RUN_ID
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
          git switch -c $PR_BRANCH
          git push -u origin $PR_BRANCH

      - name: Checkout Update Versions Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ env.PR_BRANCH }}

      - name: Update Core Version
        env:
          VERSION: ${{ needs.setup.outputs.core_version }}
        run: sed -i '/define "bitwarden.coreVersionDefault"/!b;n;c{{- "'$VERSION'" -}}' helpers.tpl
        working-directory: charts/self-host/templates

      - name: Update Web Version
        env:
          VERSION: ${{ needs.setup.outputs.web_version }}
        run: sed -i '/define "bitwarden.webVersionDefault"/!b;n;c{{- "'$VERSION'" -}}' helpers.tpl
        working-directory: charts/self-host/templates

      - name: Update Chart appVersion
        env:
          VERSION: ${{ needs.setup.outputs.core_version }}
        run: "sed -i -e 's/appVersion:.*/appVersion: '$VERSION'/' Chart.yaml"
        working-directory: charts/self-host

      - name: Commit updated files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updated core and web versions" -a

      - name: Push changes
        run: git push -u origin $PR_BRANCH

      - name: Create Update Versions PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ github.ref_name }}
          TITLE: "Update core and web versions"
        run: |
          gh pr create --title "$TITLE" \
            --base "$BASE_BRANCH" \
            --head "$PR_BRANCH" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [X] Other

              ## Objective
              Automated version updates to core and web versions in charts/self-host/templates/helpers.tpl.
              Automated version update to appVersion in charts/self-host/Chart.yaml"
